"""add generic fields and indexes to notifications

Revision ID: 4c0d0a1fb1ab
Revises: 
Create Date: 2026-05-20 08:10:04.210387

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '4c0d0a1fb1ab'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referencia_tipo', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('referencia_id', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('url_destino', sa.String(length=500), nullable=True))
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=50),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('titulo',
               existing_type=sa.String(length=150),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.create_index('idx_notificacao_referencia', ['referencia_tipo', 'referencia_id'], unique=False)
        batch_op.create_index('idx_notificacao_usuario_empresa_lida', ['usuario_id', 'empresa_id', 'lida'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacoes', schema=None) as batch_op:
        batch_op.drop_index('idx_notificacao_usuario_empresa_lida')
        batch_op.drop_index('idx_notificacao_referencia')
        batch_op.alter_column('titulo',
               existing_type=sa.String(length=255),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('tipo',
               existing_type=sa.String(length=50),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('url_destino')
        batch_op.drop_column('referencia_id')
        batch_op.drop_column('referencia_tipo')
    # ### end Alembic commands ###
